#############################################
##            MODULE VARIABLES
#############################################
print('Load key2hassio')
    
import os, sys, time, json, traceback

keyCode = {
    "a" 			: {"name": "numeric 1", "keyNum":4, "keyMod": 0},
    "b" 			: {"name": "numeric 1", "keyNum":5, "keyMod": 0},
    "c" 			: {"name": "numeric 1", "keyNum":6, "keyMod": 0},
    "d" 			: {"name": "numeric 1", "keyNum":7, "keyMod": 0},
    "e" 			: {"name": "numeric 1", "keyNum":8, "keyMod": 0},
    "f" 			: {"name": "numeric 1", "keyNum":9, "keyMod": 0},
    "g" 			: {"name": "numeric 1", "keyNum":10, "keyMod": 0},
    "h" 			: {"name": "numeric 1", "keyNum":11, "keyMod": 0},
    "i" 			: {"name": "numeric 1", "keyNum":12, "keyMod": 0},
    "j" 			: {"name": "numeric 1", "keyNum":13, "keyMod": 0},
    "k" 			: {"name": "numeric 1", "keyNum":14, "keyMod": 0},
    "l" 			: {"name": "numeric 1", "keyNum":15, "keyMod": 0},
    "m" 			: {"name": "numeric 1", "keyNum":16, "keyMod": 0},
    "n" 			: {"name": "numeric 1", "keyNum":17, "keyMod": 0},
    "o" 			: {"name": "numeric 1", "keyNum":18, "keyMod": 0},
    "p" 			: {"name": "numeric 1", "keyNum":19, "keyMod": 0},
    "q" 			: {"name": "numeric 1", "keyNum":20, "keyMod": 0},
    "r" 			: {"name": "numeric 1", "keyNum":21, "keyMod": 0},
    "s" 			: {"name": "numeric 1", "keyNum":22, "keyMod": 0},
    "t" 			: {"name": "numeric 1", "keyNum":23, "keyMod": 0},
    "u" 			: {"name": "numeric 1", "keyNum":24, "keyMod": 0},
    "v" 			: {"name": "numeric 1", "keyNum":25, "keyMod": 0},
    "w" 			: {"name": "numeric 1", "keyNum":26, "keyMod": 0},
    "x" 			: {"name": "numeric 1", "keyNum":27, "keyMod": 0},
    "y" 			: {"name": "numeric 1", "keyNum":28, "keyMod": 0},
    "z" 			: {"name": "numeric 1", "keyNum":29, "keyMod": 0},
    "1" 			: {"name": "numeric 1", "keyNum":30, "keyMod": 0},
    "2" 			: {"name": "numeric 2", "keyNum":31, "keyMod": 0},
    "3" 			: {"name": "numeric 3", "keyNum":32, "keyMod": 0},
    "4" 			: {"name": "numeric 4", "keyNum":33, "keyMod": 0},
    "5" 			: {"name": "numeric 5", "keyNum":34, "keyMod": 0},
    "6" 			: {"name": "numeric 6", "keyNum":35, "keyMod": 0},
    "7" 			: {"name": "numeric 7", "keyNum":36, "keyMod": 0},
    "8" 			: {"name": "numeric 8", "keyNum":37, "keyMod": 0},
    "9" 			: {"name": "numeric 9", "keyNum":38, "keyMod": 0},
    "0" 			: {"name": "numeric 0", "keyNum":39, "keyMod": 0},
    "Ok" 			: {"name": "dpad select", "keyNum":40, "keyMod": 0},
    "Back" 			: {"name": "previos page", "keyNum":41, "keyMod": 0},
    "Home" 			: {"name": "home page", "keyNum":41, "keyMod": 4},
    "Focus" 		: {"name": "set context", "keyNum":74, "keyMod": 0},
    "Less" 			: {"name": "media skip backward", "keyNum":75, "keyMod": 0},
    "More" 			: {"name": "media skip forward", "keyNum":78, "keyMod": 0},
    "Right" 		: {"name": "dpad right", "keyNum":79, "keyMod": 0},
    "Left" 			: {"name": "dpad left", "keyNum":80, "keyMod": 0},
    "Down" 			: {"name": "dpad down", "keyNum":81, "keyMod": 0},
    "Up" 			: {"name": "dpad up", "keyNum":82, "keyMod": 0},
    "Set" 			: {"name": "set options", "keyNum":88, "keyMod": 0},
    "Menu" 			: {"name": "options menu", "keyNum":101, "keyMod": 0},
    "OnToggle" 		: {"name": "power toggle", "keyNum":102, "keyMod": 0},
    "SoundToggle" 	: {"name": "volume mute", "keyNum":127, "keyMod": 0},
    "Louder" 		: {"name": "volume up", "keyNum":128, "keyMod": 0},
    "Softer" 		: {"name": "volume down", "keyNum":129, "keyMod": 0},
    "PlayToggle" 	: {"name": "media play", "keyNum":232, "keyMod": 0},
    "Backward" 		: {"name": "media rewind", "keyNum":234, "keyMod": 0},
    "Forward" 		: {"name": "media fast forward", "keyNum":235, "keyMod": 0},
}

usbNum = {
    1: {"keyCode": "Back"},
    28: {"keyCode": "Ok"},
    59: {"keyCode": "SoundToggle"},
    103: {"keyCode": "Up"},
    104: {"keyCode": "Less"},
    105: {"keyCode": "Left"},
    106: {"keyCode": "Right"},
    108: {"keyCode": "Down"},
    109: {"keyCode": "More"},
    113: {"keyCode": "SoundToggle"},
    114: {"keyCode": "Softer"},
    115: {"keyCode": "Louder"},
    116: {"keyCode": "PowerToggle"},
    127: {"keyCode": "Menu"},
    158: {"keyCode": "Exit"},
    163: {"keyCode": "Forward"},
    164: {"keyCode": "PlayToggle"},
    165: {"keyCode": "Backward"},
    172: {"keyCode": "Home"},
    191: {"keyCode": "Set"},
    240: {"keyCode": "Focus"},
    272: {"keyCode": "Ok"},
    273: {"keyCode": "Back"},
}

keyMod = {
    "1":   {"name": "leftShift"},
    "2":   {"name": "leftCtrl"},
    "4":   {"name": "leftAlt"},
    "8":   {"name": "leftCmd"},
    "16":  {"name": "rightShift"},
    "32":  {"name": "rightCtrl"},
    "64":  {"name": "rightAlt"},
    "128": {"name": "rightCmd"},
}
